# Code generated by Morphe
# Source: Morphe Registry

from pydantic import BaseModel
from typing import List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .comment import Comment

class Company(BaseModel):
    """Company model."""
    id: int
    name: str
    comments: Optional[List[Comment]] = None